openapi: 3.0.3
info:
  title: Cybersite 2077 API Documentation
  version: 1.0.0
  # Подключаем пути из модуля Identity:
paths:
  # api/identity/auth:
  /api/identity/auth/register:
    $ref: "./modules/identity.yaml#/paths/~1register"
  /api/identity/auth/login:
    $ref: "./modules/identity.yaml#/paths/~1login"
  /api/identity/auth/logout:
    $ref: "./modules/identity.yaml#/paths/~1logout"
  /api/identity/auth/logout-all:
    $ref: "./modules/identity.yaml#/paths/~1logout-all"
  /api/identity/auth/refresh:
    $ref: "./modules/identity.yaml#/paths/~1refresh"
  /api/identity/auth/change-password:
    $ref: "./modules/identity.yaml#/paths/~1change-password"
  /api/identity/auth/delete-account:
    $ref: "./modules/identity.yaml#/paths/~1delete-account"
  /api/identity/auth/activate/{token}:
    $ref: "./modules/identity.yaml#/paths/~1activate~1{token}"
  /api/identity/auth/forgot-password:
    $ref: "./modules/identity.yaml#/paths/~1forgot-password"
  /api/identity/auth/reset-password:
    $ref: "./modules/identity.yaml#/paths/~1reset-password"
  /api/identity/auth/2fa/setup:
    $ref: "./modules/identity.yaml#/paths/~12fa~1setup"
  /api/identity/auth/2fa/enable:
    $ref: "./modules/identity.yaml#/paths/~12fa~1enable"
  /api/identity/auth/2fa/verify:
    $ref: "./modules/identity.yaml#/paths/~12fa~1verify"
  /api/identity/auth/google/:
    $ref: "./modules/identity.yaml#/paths/~1google"
  /api/identity/auth/google/callback:
    $ref: "./modules/identity.yaml#/paths/~1google~1callback"
  # api/identity/profile:
  /api/identity/profile/me:
    $ref: "./modules/identity.yaml#/paths/~1profile~1me"
  /api/identity/profile/update:
    $ref: "./modules/identity.yaml#/paths/~1profile~1update"
  /api/identity/profile/avatar:
    $ref: "./modules/identity.yaml#/paths/~1profile~1avatar"
    # api/catalog:
  /api/catalog/categories:
    $ref: "./modules/catalog.yaml#/paths/~1categories"
  /api/catalog/brands:
    $ref: "./modules/catalog.yaml#/paths/~1brands"
  /api/catalog/motorcycles:
    $ref: "./modules/catalog.yaml#/paths/~1motorcycles"
  /api/catalog/motorcycles/{brandSlug}/{slug}:
    $ref: "./modules/catalog.yaml#/paths/~1motorcycles~1{brandSlug}~1{slug}"
  /api/catalog/search/suggest:
    $ref: "./modules/catalog.yaml#/paths/~1search~1suggest"
  /api/catalog/motorcycles/{slug}/related:
    $ref: "./modules/catalog.yaml#/paths/~1motorcycles~1{slug}~1related"
  /api/catalog/sync-search:
    $ref: "./modules/catalog.yaml#/paths/~1sync-search"
  /api/catalog/sitemap.xml:
    $ref: "./modules/catalog.yaml#/paths/~1sitemap.xml"
    # api/trading:
  /api/trading/favorites/ids:
    $ref: "./modules/trading.yaml#/paths/~1favorites~1ids"
  /api/trading/favorites/toggle/{motorcycleId}:
    $ref: "./modules/trading.yaml#/paths/~1favorites~1toggle~1{motorcycleId}"
  /api/trading/favorites/details:
    $ref: "./modules/trading.yaml#/paths/~1favorites~1details"
  /api/trading/cart:
    $ref: "./modules/trading.yaml#/paths/~1cart"
  /api/trading/cart/add:
    $ref: "./modules/trading.yaml#/paths/~1cart~1add"
  /api/trading/cart/quantity:
    $ref: "./modules/trading.yaml#/paths/~1cart~1quantity"
  /api/trading/cart/item/{motorcycleId}:
    $ref: "./modules/trading.yaml#/paths/~1cart~1item~1{motorcycleId}"
  /api/trading/cart/remove-selected:
    $ref: "./modules/trading.yaml#/paths/~1cart~1remove-selected"
  /api/trading/cart/select:
    $ref: "./modules/trading.yaml#/paths/~1cart~1select"
  /api/trading/cart/select-all:
    $ref: "./modules/trading.yaml#/paths/~1cart~1select-all"
    # api/warehouse:
  /api/warehouse:
    $ref: "./modules/warehouse.yaml#/paths/~1"
  /api/warehouse/calculate:
    $ref: "./modules/warehouse.yaml#/paths/~1calculate"
    # api/orders:
  /api/orders/:
    $ref: "./modules/ordering.yaml#/paths/~1"
  /api/orders/my:
    $ref: "./modules/ordering.yaml#/paths/~1my"
  /api/orders/active-count:
    $ref: "./modules/ordering.yaml#/paths/~1active-count"
  /api/orders/{orderId}/complete:
    $ref: "./modules/ordering.yaml#/paths/~1{orderId}~1complete"
  /api/orders/{orderId}/cancel:
    $ref: "./modules/ordering.yaml#/paths/~1{orderId}~1cancel"
  /api/orders/{orderId}/pay-test:
    $ref: "./modules/ordering.yaml#/paths/~1{orderId}~1pay-test"
    # api/reviews:
  /api/reviews/:
    $ref: "./modules/reviews.yaml#/paths/~1"
  /api/reviews/{motorcycleId}:
    $ref: "./modules/reviews.yaml#/paths/~1{motorcycleId}"
  /api/reviews/{reviewId}:
    $ref: "./modules/reviews.yaml#/paths/~1{reviewId}"
    # api/discount:
  /api/discount/global:
    $ref: "./modules/discount.yaml#/paths/~1global"
  /api/discount/all-promos:
    $ref: "./modules/discount.yaml#/paths/~1all-promos"
  /api/discount/apply-promo:
    $ref: "./modules/discount.yaml#/paths/~1apply-promo"
  /api/discount/force-generate:
    $ref: "./modules/discount.yaml#/paths/~1force-generate"
    # api/payment:
  /api/payment/webhook:
    $ref: "./modules/payment.yaml#/paths/~1webhook"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
