server {
    listen 80;
    server_name localhost

     # Увеличиваем лимиты на заголовки, куки и размер запроса:
    large_client_header_buffers 4 16k;
    client_header_buffer_size 1k;
    client_max_body_size 20M;

    # Включаем сжатие:
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/javascript text/xml image/svg+xml;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;



    # Кэширование статики (изображения, иконки, шрифты)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?|eot|ttf|otf)$ {
        root /usr/share/nginx/html;
        expires 30d;          # Кэшируем на 30 дней
        add_header Cache-Control "public, no-transform";
        access_log off;       # Не забиваем логи запросами за картинками
    }

    # Прокси на бэкенд:
    location /api/ {
        # host.docker.internal — это IP сновного компьютера изнутри докера //Для локальной разработки
        # proxy_pass http://host.docker.internal:3001;  //Для локальной разработки
        proxy_pass http://server:3001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Проки на бэкенд для статики:
    location /static/ {
        # proxy_pass http://host.docker.internal:3001/static/; //Для локальной разработки
        proxy_pass http://server:3001/static/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Прокси на фронтенд:
    location / {
        # proxy_pass http://host.docker.internal:5173; //Для локальной разработки

        # (Prod) Папка, из которой Nginx будет брать и отдавать файлы для фронтенда (эту папку указали в docker-compose):
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Следующие два блока закомментировать для использования docker-compose.prod.yml:
    # Прокси на Grafana:
    location /grafana/ {
        proxy_pass http://grafana:3000/;
    }

    # Прокси на Tempo:
    location /tempo/ {
        proxy_pass http://tempo:3200/;
    }
}
