server {
    listen 80;
    server_name cybersite2077.online www.cybersite2077.online;

    # Увеличиваем лимиты на заголовки, куки и размер запроса:
    large_client_header_buffers 4 16k;
    client_header_buffer_size 1k;
    client_max_body_size 20M;

    # Включаем сжатие:
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/javascript text/xml image/svg+xml;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;

    # Проки на бэкенд для статики:
    location ^~ /static/ { 
        # Для сборки проекта в контейнеры: 
        proxy_pass http://server:3001/static/; 
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Кэшируем файлы из бэкенда в браузере пользователя на 30 дней:
        expires 30d; 
        add_header Cache-Control "public, no-transform"; 
        access_log off; 
    } 

    # Кэширование статики файлов фронтенда
    location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?|eot|ttf|otf|webp)$ { 
        root /usr/share/nginx/html; 
        expires 30d; 
        add_header Cache-Control "public, no-transform"; 
        access_log off; 
        
        # Если файла сборки фронтенда нет на диске, отдаем 404 (запросы /static/ сюда уже не попадут)
        try_files $uri =404;
    } 

    # Прокси на бэкенд:
    location /api/ {
        proxy_pass http://server:3001; 
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Прокси на фронтенд:
    location / {
        # (Prod) Папка, из которой Nginx будет брать и отдавать файлы для фронтенда (эту папку указал в docker-compose):
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;

        # proxy_http_version 1.1;
        # proxy_set_header Host $host;
        # proxy_set_header Upgrade $http_upgrade;
        # proxy_set_header Connection "upgrade";

        # proxy_set_header X-Real-IP $remote_addr;
        # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

}
