services:
  # ------------Инфраструктура:--------------- #
  nginx:
    image: ghcr.io/valeriytm/cybersite-nginx:latest
    container_name: cybersite_nginx_prod
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
    # Общие папки для сертификатов:
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/www/certbot
    networks:
      - cybersite_net
    depends_on:
      - server
  # ------------Бэкенд:--------------- #
  server:
    image: ghcr.io/valeriytm/cybersite-server:latest
    container_name: cybersite_server_prod
    restart: always
    env_file: .env.prod # Будет лежать в той же папке на VPS
    depends_on:
      - postgres
      - redis
      - mongodb
    networks:
      - cybersite_net

  # ------------Базы данных:--------------- #

  # Основная база: PostgreSQL с расширением PostGIS для реализации карты
  postgres:
    image: postgis/postgis:15-3.3
    container_name: cybersite_postgres_prod
    restart: always
    env_file:
      - .env.prod # Файл из корня проекта
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cybersite_net

  # Кэш и очереди: Redis (для корзины и BullMQ)
  redis:
    image: redis:7-alpine
    container_name: cybersite_redis_prod
    restart: always
    volumes:
      - redis_data:/data
    env_file:
      - .env.prod # Файл из корня проекта
    networks:
      - cybersite_net

  # MongoDB (для отзывов и новостей)
  mongodb:
    image: mongo:6.0
    container_name: cybersite_mongodb_prod
    restart: always
    env_file:
      - .env.prod # Файл из корня проекта
    volumes:
      - mongodb_data:/data/db
    networks:
      - cybersite_net

  # Поисковый движок:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    container_name: cybersite_elasticsearch_prod
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - cybersite_net

    # --------------------------------------------------- #
  adminer:
    image: adminer
    container_name: cybersite_adminer
    restart: always
    ports:
      - "127.0.0.1:8085:8080" # Буду подключаться через SSH
    networks:
      - cybersite_net

    # --------------------------------------------------- #

  certbot:
    image: certbot/certbot
    container_name: cybersite_certbot_prod
    # Делим те же папки с Nginx:
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/www/certbot
    # Команда для получения сертификата (в первый запуск она создаст ключи)
    # Замените домен и email на свои!
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot certonly --webroot -w /var/www/certbot d cybersite2077.online d www.cybersite2077.online email tamvalera@gmail.com rsa-key-size 4096 agree-tos non-interactive; sleep 12h & wait $${!}; certbot renew; done'"
    networks:
      - cybersite_net

  # --------------------------------------------------- #

networks:
  cybersite_net:
    driver: bridge

volumes:
  # Для PostgreSQL:
  postgres_data:
  # Для Redis:
  redis_data:
  # Для MongoDB:
  mongodb_data:
  # Для Elascticsearch:
  es_data:
  # Для Certbot:
  certbot_etc:
  certbot_var:
