# version: "3.8"

services:
  # ------------Инфраструктура:--------------- #
  nginx:
    build: ./nginx
    container_name: cybersite_nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
    volumes:
      # Nginx отдаёт файлы фронтенда напрямую:
      - ../apps/web/dist:/usr/share/nginx/html
    networks:
      - cybersite_net
    depends_on:
      - grafana
      - server
  # ------------Фронтенд и бэкенд:--------------- #
  server:
    build:
      context: .. # Поднимаемся в корень проекта
      dockerfile: Dockerfile
      target: server # Выбираем стадию бэкенда
    container_name: cybersite_server
    env_file: ../.env # Файл из корня
    depends_on:
      - postgres
      - redis
      - mongodb
    networks:
      - cybersite_net

  # ------------Базы данных:--------------- #

  # Основная база: PostgreSQL с расширением PostGIS для реализации карты
  postgres:
    image: postgis/postgis:15-3.3 # Специальный образ с уже установленным PostGIS
    container_name: cybersite_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cybersite_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cybersite_net

  # Кэш и очереди: Redis (для корзины и BullMQ)
  redis:
    image: redis:7-alpine
    container_name: cybersite_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - cybersite_net

  # MongoDB (для отзывов и новостей)
  mongodb:
    image: mongo:6.0
    container_name: cybersite_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - cybersite_net

  # Поисковый движок:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    container_name: cybersite_elasticsearch
    restart: always
    environment:
      - node.name=es-node-01
      - cluster.name=cybersite-search
      - discovery.type=single-node
      # Полное отключение безопасности для локальной разработки:
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      # Настройки CORS для браузера:
      - http.cors.enabled=true
      - 'http.cors.allow-origin="*"'
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization
      # Лимиты памяти:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - cybersite_net

  # ------------Мониторинг:--------------- #

  # Визуализация и мониторинг (дашборды):
  grafana:
    image: grafana/grafana:latest
    container_name: cybersite_grafana
    restart: always
    ports:
      - "3050:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - cybersite_net
    depends_on:
      - elasticsearch
      - loki
      - prometheus

  loki:
    image: grafana/loki:latest
    container_name: cybersite_loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - cybersite_net

  prometheus:
    image: prom/prometheus:latest
    container_name: cybersite_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - cybersite_net
  # ------------Утилиты:--------------- #
  # Веб-интерфейс для просмотра таблиц PostgreSQL
  adminer:
    image: adminer
    container_name: cybersite_adminer
    restart: always
    ports:
      - "8085:8080"
    networks:
      - cybersite_net

    # Веб-интерфейс для управления MongoDB
  mongo-express:
    image: mongo-express
    container_name: cybersite_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: dev
      ME_CONFIG_BASICAUTH_PASSWORD: dev
    networks:
      - cybersite_net
    depends_on:
      - mongodb

  # Веб-интерфейс для управления Redis:
  redis-insight:
    image: redis/redisinsight:latest
    container_name: cybersite_redis_insight
    restart: always
    ports:
      - "5540:5540"
    networks:
      - cybersite_net
    depends_on:
      - redis
  # --------------------------------------------------- #
networks:
  cybersite_net:
    driver: bridge

volumes:
  # Для PostgreSQL:
  postgres_data:
  # Для Redis:
  redis_data:
  # Для MongoDB:
  mongodb_data:
  # Для Elascticsearch:
  es_data:
  # Для Grafana:
  grafana_data:
